In this notebook, we're going to cover some of the most fundamental concepts of tensors using tensorflow
More specifically , we're cover :
*introduction to tensor
* getting information to tensors
*manipulating tensors


## introduction to tensors

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)


2.14.0


In [4]:
#creating tensors with tf.constant()

scalar = tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# check the number of dimensions of a tensor ndim stands for number of dimensions
scalar.ndim

0

In [6]:
#create a vector

vector  = tf.constant([10,10])

vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
#check the dimension of our vector
vector.ndim

1

In [8]:
# create a mmatrix

matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
# create anotther matrix
another_matrix = tf.constant([[10.,7.],[3.,2.],[8.,9.]], dtype =tf.float16)

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [11]:
another_matrix.ndim

2

In [12]:
#Let's create a tensor

tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                     [[7,8,9],
                      [10,11,12]],
                     [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [13]:
tensor.ndim


3

what we have created so far:
* Scalar : is a single number
* Vector :  a number with direction (e.g wind speed and diretion)
* matrix :  a 2-dimensional array of numbers
* tensor : an n-dimention array of numbers when n can be any numeber , a 0-dimensional tensor is scalar and a i dimensional tenso is a vector  

In [14]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [15]:
 #create the same tenso with tf.variable as above
changeable_tensor = tf.Variable([10, 7])
unchageable_tensor = tf.constant([10,7])

changeable_tensor, unchageable_tensor



(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [16]:
#  change one of th elemets  in our changeable tensor

# changeable_tensor[0]=7
# changeable_tensor

In [17]:
# How  about we try .assign

changeable_tensor[0].assign(7)

changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [18]:
#  try changing the unchangable tensor

# unchageable_tensor[0].assign(7)
# unchageable_tensor

Creating random tensors


Random tensor are tensors of some arbitary size that contains random numbers


In [19]:
#  create two random of the same tensor
random_1 = tf.random.Generator.from_seed(4) #set seed reproducibilty
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(4)
random_2 = random_2.normal(shape =(3,2))

#  are they equal
random_1,random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 1.0019135 ,  0.67351365],
        [ 0.06987712, -1.4077919 ],
        [ 1.0278524 ,  0.27974114]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 1.0019135 ,  0.67351365],
        [ 0.06987712, -1.4077919 ],
        [ 1.0278524 ,  0.27974114]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order in the elements of a tensor


In [20]:
# shuffle a tensor( this valuable when you want to shuffle yor data so that the inhenrent order doest affect your result)

not_Shuffled = tf.constant([[10,7],[3,4],[2,5]])
#   shuffle the non shuffle
tf.random.shuffle(not_Shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [21]:
tf.random.set_seed(42)
tf.random.shuffle(not_Shuffled, seed=42)



<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [22]:
# tf.random.set_seed(445)

# tf.random.shuffle(not_Shuffle , seed=100)

In [23]:
tf.random.set_seed (42) # global level random seed
tf.random.shuffle(not_Shuffled , seed =42) # operation level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

# Other ways to make tensors


In [24]:
# create a tensonr of all ones
tf.ones([10,4])

<tf.Tensor: shape=(10, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [25]:
#  creating a tensor of zeros
tf.zeros(shape = (3,4))


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into tensors

The main difference between Numpy arrays and tensorflow  tensors is that
tensors can be ran  on a GPU (much Faster for numnerical computing)


In [26]:
#  you can also turn numpy arrays into tensors

import numpy as np
numpy_A = np.arange(1,25, dtype = np.int32)  # create a numpy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix) #capital for matrix or tensot
# y = tf.contant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [27]:
A =tf.constant(numpy_A , shape=(3,8))
B =tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [28]:
A.ndim

2

### Getting informaition from tensors
When dealing with tensors you probably want to be aware of the following


* Shape
* Rank
* Axis and dimension
* Size

In [29]:
#  create a rank 4 Tensor

rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [30]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [31]:
rank_4_tensor.shape, rank_4_tensor.ndim ,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [32]:
#  get various attributes of tensors

print("Datatype of evevry element :" , rank_4_tensor.dtype)
print("Number if dimensions (rank)" , rank_4_tensor.ndim)
print("Shape of tensor:" ,rank_4_tensor.shape)
print("Elements along the  0 axis :", rank_4_tensor.shape[0])
print("Elements along the last axis :" ,rank_4_tensor.shape[-1])
print("Total number of  elements in our tensor", tf.size(rank_4_tensor).numpy())


Datatype of evevry element : <dtype: 'float32'>
Number if dimensions (rank) 4
Shape of tensor: (2, 3, 4, 5)
Elements along the  0 axis : 2
Elements along the last axis : 5
Total number of  elements in our tensor 120


### Indexing tensors
Tensors can be indexed just like Python lists

In [33]:
some_list = [1,2,3,4]

some_list[:2]

[1, 2]

In [34]:
#  Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]


<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [35]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [36]:
#  getting first element from each dimension from each index except the final one

rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [37]:
# Create a rank 2 tensor

rank_2_tensor =  tf.constant([[10,7],[3,4]])

rank_2_tensor.shape ,rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [38]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [39]:
#  get the last item of each row of our rank 2 tensor

rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [40]:
# Adding extra dimensions to our rank 2 tensor

rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [41]:
# alternative to tf.newaxis
tf.expand_dims(rank_2_tensor , axis =-1) # expanding the last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [42]:
tf.expand_dims(rank_2_tensor , axis =0) # expand the first axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [43]:
tf.expand_dims(rank_2_tensor , axis =1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

### Manipulating tensors (tensor operation)
**Basic Operations**
+,-,*,/

In [44]:
# the additional operator

tensor = tf.constant([[10, 7],[3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [45]:
# the  original tensor is unchanged

tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [46]:
# Multiplication operator
tensor *10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [47]:
# subtraction
tensor -10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [48]:
#  we can use the tensorflow builtin function

tf.math.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [49]:
#  use tf.math operator for speed

tf.math.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [50]:
tf.math.divide(tensor , 10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [51]:

tf.math.subtract(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

### Matrix multiplication

In machine learning matrix multiplications is
one the most used commands

There are two rules our tensors (or matrices) need to fulfil if we're going to matrix multiply them:
1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions

In [52]:
#  Matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor,tensor)


tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [53]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [54]:
# Matrix multiplication with tf.matmul

a = tf.constant([[1 ,2 ,5],
                 [7 ,2 ,1],
                 [3 ,3 ,3]])

b = tf.constant([[3, 5],
                 [6, 7],
                 [1, 8]])
a.shape ,b.shape

(TensorShape([3, 3]), TensorShape([3, 2]))

In [55]:

tf.matmul(a,b)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [56]:
#  Matrix multiplication with python Using the "@" operator

a @ b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [57]:
#  create a tendo of (3,2)
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]
                ])
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X,Y


(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [58]:

# Try multiplying a that have the same dimenrion
# tf.matmul(X,Y)

In [59]:
tf.reshape(Y, shape =(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [60]:
X.shape, Y.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [61]:
X @ tf.reshape(Y, shape =(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [62]:
tf.matmul(X,tf.reshape(Y, shape =(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

** The dot product **
Matrix multiplication is also referrred to as the dot product.

You can perform matrix multiplication using:

* tf.matmul()
* tf.tensordot()
* @

In [63]:
#perform a the dot product  on x and y

tf.tensordot(tf.transpose(X),Y,axes =1 )

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [64]:
#  perform matrix multiplication with y transposed
tf.matmul(X ,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [65]:
#  perform matrix multipication between X and Y(reshaped)

tf.matmul(X, tf.reshape(Y, shape= (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [66]:
#  checkt the values of Y , reshape  Y and Transpose Y

print("Normal Y:")
print(Y.numpy(), "\n")

print("Y reshaped :")
print(tf.reshape(Y, shape=(2,3)).numpy(), "\n")

print("Y transpose :")
print(tf.transpose(Y).numpy())

Normal Y:
[[ 7  8]
 [ 9 10]
 [11 12]] 

Y reshaped :
[[ 7  8  9]
 [10 11 12]] 

Y transpose :
[[ 7  9 11]
 [ 8 10 12]]


Generally, when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will tranpose (rather than reshape) one of the tensors to get satisify the matrix multiplication rules.

### Changing the datatype of a Tensor

In [67]:
#  create a new tensor with the default dtype  int32
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [68]:
C= tf.constant([7,6])
C.dtype

tf.int32

In [69]:
B  = tf.cast(B, dtype= tf.float16)

B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [70]:
e= tf.cast(C, dtype= tf.float32)
e , e.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([7., 6.], dtype=float32)>,
 tf.float32)

### Aggregating  tensors
Aggregating tensors = condensing them from multiple values down to a smaller amount of values.

In [71]:
tf.__version__

'2.14.0'

In [72]:
#  Get the absolute values

D = tf.constant([-7 ,-10])
D, C


(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 6], dtype=int32)>)

In [73]:
#  get absolute values
tf.math.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following form of aggregatation :
* Get the maximum
* Get the minimum
* Get the mean
* Get the sum

In [76]:
# find the maximum
tf.math.reduce_max(E).numpy()


98

In [77]:
# find the maximum
tf.math.reduce_min(E).numpy()

10

In [78]:
#  Find the mean
tf.math.reduce_mean(E).numpy()

54

In [79]:
# Find the sum
tf.math.reduce_sum(E).numpy()

2737

In [75]:
#create a random tensor with values between 0 and 100 th siize of 50

E  = tf.constant(np.random.randint(0 ,100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([40, 85, 76, 58, 33, 57, 26, 37, 92, 46, 87, 58, 12, 30, 50, 72, 36,
       25, 25, 86, 17, 94, 13, 23, 60, 36, 36, 62, 36, 66, 60, 76, 59, 98,
       83, 72, 25, 10, 45, 97, 85, 87, 59, 34, 72, 15, 90, 46, 96, 54])>

In [81]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [82]:
# find the minimum
np.min(E),


(10,)

In [83]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=10>

🔨Solution

In [84]:
F= tf.cast(E, tf.float32)
tf.math.reduce_std(F)

#  to use the standard deviation, you must convert you values to float



<tf.Tensor: shape=(), dtype=float32, numpy=26.114985>

In [85]:
E.dtype

tf.int64

In [86]:
tf.math.reduce_variance(F)

#  to use varience  convert the dtype from int to float

<tf.Tensor: shape=(), dtype=float32, numpy=681.99243>

In [87]:
import tensorflow_probability as tfp
tfp.stats.variance(F)


<tf.Tensor: shape=(), dtype=float32, numpy=681.99243>

### **Find the positional maximum and minmum**

In [88]:
#  create a new tensor for finding  positional min and max
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F


<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [89]:
#  find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [90]:
np.argmax(F)

42

In [91]:
#  Index on our larges value postion
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [92]:
# find the max value of F

tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [93]:
# check for equlity

F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [94]:
# find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [95]:
#  find the minimum using the positional minimum index

F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [96]:
#  find the min valu of F

tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [97]:
#  check for equity
F[tf.argmin(F)] == tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Squeezing  a tensor(removing all single dimensions)

In [98]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [99]:
 G.shape

TensorShape([1, 1, 1, 1, 50])

In [100]:
G_squeezed= tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-hot Encoding Tensors

In [101]:
#  create a list of indices
some_list = [0,1,2,3]
depth = 4
# One hot encode  our  list  of indicees
tf.one_hot(some_list , depth)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [102]:
# specify custom values for one hot encoding
tf.one_hot(some_list , depth =4, on_value="yo I love deep learning", off_value= "mad")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love deep learning', b'mad', b'mad', b'mad'],
       [b'mad', b'yo I love deep learning', b'mad', b'mad'],
       [b'mad', b'mad', b'yo I love deep learning', b'mad'],
       [b'mad', b'mad', b'mad', b'yo I love deep learning']], dtype=object)>

### Other mathmatical operations

In [103]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [104]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [105]:
tf.math.sqrt(tf.cast(H , dtype= tf.float32)).numpy()

array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)

In [106]:
# find the log
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [107]:
# rounding up numbers

tf.math.round(tf.math.sqrt(tf.cast(H, dtype=tf.float32)),name =None)

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 1., 2., 2., 2., 2., 3., 3., 3.], dtype=float32)>

In [108]:
# flor divisin

tf.math.floordiv(
  102,4, name = None
).numpy()

25

### Tensors an  Numpy
Tensorfloee interacte well  with numpy

In [109]:
#

J =tf.constant(np.array([3.,7.,10.]))
J


<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [110]:
# convert to np array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [111]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [112]:
# default types of each are slightly diff

numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])


#  check the dtype
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to gpu

In [5]:
tf.config.list_logical_devices()

[LogicalDevice(name='/device:CPU:0', device_type='CPU')]

: 

In [2]:
!nvidia-smi

NVIDIA-SMI has failed because you are not:
	a) running as an administrator or
	b) there is not at least one TCC device in the system

